solve 'repeated gets' problem which also exposes an elm error
This code without the dropRepeats produces a constant filename signal at
~2 Hz that I can't figure out where it is updating from, which also
results in an error in the Elm produced javascript code:

TypeError: result is undefined Main.elm:10308:10

Where Main.elm:10308 is in function stepTask and looks like:

		if (tag === 'AndThen' || tag === 'Catch')
		{
			var result = mark('runnable', task.task);
>>>>>>>>		while (result.status === 'runnable')
			{
				result = stepTask(onComplete, root, result.task);
			}